teste 03

diff --git a/package/dropbear/S50dropbear b/package/dropbear/S50dropbear
--- a/package/dropbear/S50dropbear
+++ b/package/dropbear/S50dropbear
@@ -6,15 +6,7 @@
 # Allow a few customizations from a config file
 test -r /etc/default/dropbear && . /etc/default/dropbear
 
-systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
-
 start() {
-        enabled="`$systemsetting  -command load -key system.ssh.enabled`"
-        if [ "$enabled" == "0" ];then
-          echo "SSH services: disabled"
-          exit 0
-        fi
-
 	DROPBEAR_ARGS="$DROPBEAR_ARGS -R"
 
 	# If /etc/dropbear is a symlink to /var/run/dropbear, and
@@ -44,7 +36,7 @@ start() {
 stop() {
 	printf "Stopping dropbear sshd: "
 	start-stop-daemon -K -q -p /var/run/dropbear.pid
-	start-stop-daemon -K -q -n dropbear
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 restart() {
 	stop
